[ids]

# device id from keyd monitor
0001:0001:3cf016cc

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)

# Remaps the escape key to capslock
esc = capslock

# Remaps the print screen to right meta
sysrq = rightmeta
